/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description The process is up. Deliberately checks nothing else, so a database blip
         *     doesn't get every container restarted by its healthcheck.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Can this process do real work? 503 names whatever is unreachable.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_auth_verify_email_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_me_patch"];
        trace?: never;
    };
    "/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_catalog_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/service-types/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Service Type */
        get: operations["get_service_type_catalog_service_types__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/neighbourhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Neighbourhoods */
        get: operations["list_neighbourhoods_neighbourhoods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Vendors */
        get: operations["search_vendors_search_vendors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Popular Vendors
         * @description Vendors who work here, most completed jobs first. For the home page.
         */
        get: operations["popular_vendors_search_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Booking
         * @description One review per completed booking.
         */
        post: operations["review_booking_bookings__booking_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/awaiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Awaiting Review
         * @description Completed bookings you haven't reviewed yet: the prompt to leave one.
         */
        get: operations["awaiting_review_reviews_awaiting_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vendor Reviews
         * @description Published reviews for a vendor, newest first. No sign-in needed.
         */
        get: operations["vendor_reviews_vendors__slug__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vendor */
        get: operations["get_vendor_vendors__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["list_bookings_bookings_get"];
        put?: never;
        /** Create Booking */
        post: operations["create_booking_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking_bookings__booking_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vendor Contact
         * @description The vendor's contact details, available once the booking is confirmed.
         */
        get: operations["get_vendor_contact_bookings__booking_id__contact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Booking
         * @description Free until work starts. After that, report a problem instead.
         */
        post: operations["cancel_booking_bookings__booking_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/price-change/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Price Change */
        post: operations["approve_price_change_bookings__booking_id__price_change_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/price-change/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline Price Change
         * @description Cancels the booking with no penalty. On a callout booking, only the callout fee is owed.
         */
        post: operations["decline_price_change_bookings__booking_id__price_change_decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Booking Photos */
        get: operations["list_booking_photos_bookings__booking_id__photos_get"];
        put?: never;
        /** Add Booking Photo */
        post: operations["add_booking_photo_bookings__booking_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** File Report */
        post: operations["file_report_bookings__booking_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Reports */
        get: operations["my_reports_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Report */
        get: operations["my_report_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_conversations__conversation_id__messages_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_conversations__conversation_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Push Config */
        get: operations["push_config_notifications_push_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Push Subscription
         * @description Register this device for Web Push. Safe to call on every app start.
         */
        put: operations["save_push_subscription_notifications_push_subscription_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push/subscription/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove Push Subscription */
        post: operations["remove_push_subscription_notifications_push_subscription_remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_notifications_preferences_get"];
        /**
         * Set Preferences
         * @description In-app notifications are always on; email can be turned off.
         */
        put: operations["set_preferences_notifications_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Accepts the file and queues it for processing. Poll `GET /media/{id}`
         *     until `status` is `ready` (or `rejected`, with a reason).
         */
        post: operations["upload_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media */
        get: operations["get_media_media__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AwaitingReviewOut */
        AwaitingReviewOut: {
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Booking Reference */
            booking_reference: string;
            /** Vendor Name */
            vendor_name: string;
            /** Service Name */
            service_name: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** Body_upload_media_post */
        Body_upload_media_post: {
            kind: components["schemas"]["MediaKind"];
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * BookingActor
         * @enum {string}
         */
        BookingActor: "customer" | "vendor" | "admin" | "system";
        /**
         * BookingEventOut
         * @description The timeline. Who acted is shown by role, not by account.
         */
        BookingEventOut: {
            /** Action */
            action: string;
            from_status: components["schemas"]["BookingStatus"] | null;
            to_status: components["schemas"]["BookingStatus"];
            actor_type: components["schemas"]["BookingActor"];
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BookingIn */
        BookingIn: {
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
            /** Service Type Id */
            service_type_id: number;
            /**
             * Price Item Id
             * @description Omit to request a quote.
             */
            price_item_id?: string | null;
            /**
             * Description
             * @description What needs doing.
             */
            description: string;
            /** Preferred At */
            preferred_at?: string | null;
            /**
             * Is Emergency
             * @default false
             */
            is_emergency: boolean;
            /**
             * Lat
             * @description The job location pin.
             */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Address Text
             * @description Shared with the vendor only once they confirm.
             */
            address_text: string;
            /**
             * Access Notes
             * @description Gate, floor, landmark.
             */
            access_notes?: string | null;
            /**
             * Contact Phone
             * @description Defaults to your account phone.
             */
            contact_phone?: string | null;
        };
        /** BookingPhotoOut */
        BookingPhotoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            phase: components["schemas"]["BookingPhotoPhase"];
            uploaded_by: components["schemas"]["BookingActor"];
            media_status: components["schemas"]["MediaStatus"];
            /** Rejected Reason */
            rejected_reason: string | null;
            /** Urls */
            urls: {
                [key: string]: string;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * BookingPhotoPhase
         * @enum {string}
         */
        BookingPhotoPhase: "before" | "after";
        /**
         * BookingStatus
         * @enum {string}
         */
        BookingStatus: "pending" | "confirmed" | "awaiting_price_approval" | "in_progress" | "completed" | "declined" | "expired" | "cancelled";
        /** CancelIn */
        CancelIn: {
            /** Reason */
            reason?: string | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Icon */
            icon: string | null;
            /** Vendor Count */
            vendor_count: number;
            /** Service Types */
            service_types: components["schemas"]["ServiceTypeSummary"][];
        };
        /** CategorySummary */
        CategorySummary: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Icon */
            icon: string | null;
        };
        /** CodeIn */
        CodeIn: {
            /** Code */
            code: string;
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Booking Reference */
            booking_reference: string;
            booking_status: components["schemas"]["BookingStatus"];
            /** Service Name */
            service_name: string;
            /** Other Party Name */
            other_party_name: string;
            /** Is Locked */
            is_locked: boolean;
            /** Last Sequence No */
            last_sequence_no: number;
            /** Last Message At */
            last_message_at: string | null;
            /** Unread Count */
            unread_count: number;
        };
        /**
         * CustomerBookingOut
         * @description The customer's own booking. Vendor contact details come from the
         *     reveal endpoint once the booking is confirmed (issue 013).
         */
        CustomerBookingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            status: components["schemas"]["BookingStatus"];
            vendor: components["schemas"]["VendorRef"];
            service: components["schemas"]["ServiceRef"];
            pricing_model: components["schemas"]["PricingModel"];
            /** Agreed Price Kes */
            agreed_price_kes: number | null;
            /** Is Emergency */
            is_emergency: boolean;
            /** Preferred At */
            preferred_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Address Text */
            address_text: string;
            /** Access Notes */
            access_notes: string | null;
            /** Contact Phone */
            contact_phone: string;
            /** Callout Fee Kes */
            callout_fee_kes: number | null;
            /** Final Price Kes */
            final_price_kes: number | null;
            /** Warranty Days */
            warranty_days: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
            cancelled_by: components["schemas"]["BookingActor"] | null;
            /** Cancellation Reason */
            cancellation_reason: string | null;
            /** Revisions */
            revisions: components["schemas"]["PriceRevisionOut"][];
            /** Price Lines */
            price_lines: components["schemas"]["PriceLineOut"][];
            /** Events */
            events: components["schemas"]["BookingEventOut"][];
        };
        /** CustomerBookingSummary */
        CustomerBookingSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            status: components["schemas"]["BookingStatus"];
            vendor: components["schemas"]["VendorRef"];
            service: components["schemas"]["ServiceRef"];
            pricing_model: components["schemas"]["PricingModel"];
            /** Agreed Price Kes */
            agreed_price_kes: number | null;
            /** Is Emergency */
            is_emergency: boolean;
            /** Preferred At */
            preferred_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ForgotPasswordIn */
        ForgotPasswordIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MediaKind
         * @enum {string}
         */
        MediaKind: "avatar" | "portfolio" | "booking_photo" | "verification_doc";
        /** MediaOut */
        MediaOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["MediaKind"];
            status: components["schemas"]["MediaStatus"];
            /** Rejected Reason */
            rejected_reason: string | null;
            /** Mime Type */
            mime_type: string;
            /** Byte Size */
            byte_size: number;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Urls */
            urls: {
                [key: string]: string;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MediaStatus
         * @enum {string}
         */
        MediaStatus: "pending" | "ready" | "rejected";
        /** MessageIn */
        MessageIn: {
            /** Body */
            body: string;
            /**
             * Client Id
             * @description Makes retries safe.
             */
            client_id?: string | null;
        };
        /**
         * MessageKind
         * @enum {string}
         */
        MessageKind: "text" | "system";
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Sequence No */
            sequence_no: number;
            /**
             * Sender Role
             * @enum {string}
             */
            sender_role: "customer" | "vendor" | "system";
            kind: components["schemas"]["MessageKind"];
            /** Body */
            body: string;
            moderation: components["schemas"]["ModerationAction"];
            /** Client Id */
            client_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MessagesOut */
        MessagesOut: {
            /** Items */
            items: components["schemas"]["MessageOut"][];
            /** Has More */
            has_more: boolean;
            /** Last Sequence No */
            last_sequence_no: number;
            /** Is Locked */
            is_locked: boolean;
        };
        /**
         * ModerationAction
         * @enum {string}
         */
        ModerationAction: "allowed" | "redacted";
        /** NeighbourhoodOut */
        NeighbourhoodOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** County */
            county: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Is Launch Area */
            is_launch_area: boolean;
        };
        /** NeighbourhoodRef */
        NeighbourhoodRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** NotificationOut */
        NotificationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Template */
            template: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Data */
            data: Record<string, never>;
            /** Read At */
            read_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NotificationsOut */
        NotificationsOut: {
            /** Items */
            items: components["schemas"]["NotificationOut"][];
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Unread Count */
            unread_count: number;
        };
        /** OfferedService */
        OfferedService: {
            /** Service Type Id */
            service_type_id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Price Items */
            price_items: components["schemas"]["PublicPriceItem"][];
        };
        /** OwnReviewOut */
        OwnReviewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rating */
            rating: number;
            /** Comment */
            comment: string | null;
            /** Customer First Name */
            customer_first_name: string;
            /** Service Name */
            service_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Booking Reference */
            booking_reference: string;
            /** Is Published */
            is_published: boolean;
        };
        /** Page[ConversationOut] */
        Page_ConversationOut_: {
            /** Items */
            items: components["schemas"]["ConversationOut"][];
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[CustomerBookingSummary] */
        Page_CustomerBookingSummary_: {
            /** Items */
            items: components["schemas"]["CustomerBookingSummary"][];
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[PublicReviewOut] */
        Page_PublicReviewOut_: {
            /** Items */
            items: components["schemas"]["PublicReviewOut"][];
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[ReportOut] */
        Page_ReportOut_: {
            /** Items */
            items: components["schemas"]["ReportOut"][];
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** PhotoIn */
        PhotoIn: {
            /**
             * Media Id
             * Format: uuid
             */
            media_id: string;
            phase: components["schemas"]["BookingPhotoPhase"];
        };
        /** PreferencesIn */
        PreferencesIn: {
            /** Email Notifications */
            email_notifications: boolean;
        };
        /** PreferencesOut */
        PreferencesOut: {
            /** Email Notifications */
            email_notifications: boolean;
        };
        /**
         * PriceItemType
         * @enum {string}
         */
        PriceItemType: "fixed" | "callout";
        /** PriceLineOut */
        PriceLineOut: {
            /** Revision No */
            revision_no: number;
            /** Label */
            label: string;
            /** Source */
            source: string;
            /** Qty */
            qty: number;
            /** Unit Price Kes */
            unit_price_kes: number;
            /** Amount Kes */
            amount_kes: number;
        };
        /** PriceRevisionOut */
        PriceRevisionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision No */
            revision_no: number;
            /** From Kes */
            from_kes: number;
            /** To Kes */
            to_kes: number;
            /** Delta Pct */
            delta_pct: number | null;
            /** Reason Code */
            reason_code: string;
            /** Reason Label */
            reason_label: string;
            /** Reason Text */
            reason_text: string | null;
            status: components["schemas"]["RevisionStatus"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Responded At */
            responded_at: string | null;
            /** Evidence Urls */
            evidence_urls: {
                [key: string]: string;
            } | null;
        };
        /**
         * PricingModel
         * @description How a price item for this service is usually priced. Vendors choose per
         *     item; this is the default the vendor app suggests.
         * @enum {string}
         */
        PricingModel: "fixed" | "callout" | "quote";
        /** ProfileUpdateIn */
        ProfileUpdateIn: {
            /** Full Name */
            full_name?: string | null;
            /**
             * Phone
             * @example 0712 345 678
             */
            phone?: string | null;
        };
        /** PublicPortfolioItem */
        PublicPortfolioItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Caption */
            caption: string | null;
            /** Service Type Id */
            service_type_id: number | null;
            /** Urls */
            urls: {
                [key: string]: string;
            };
        };
        /** PublicPriceItem */
        PublicPriceItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            price_type: components["schemas"]["PriceItemType"];
            /** Price Kes */
            price_kes: number;
            /** Warranty Days */
            warranty_days: number;
            /** Suggested Label Id */
            suggested_label_id: number | null;
        };
        /**
         * PublicReviewOut
         * @description Shown on vendor profiles. The customer is identified by first name only.
         */
        PublicReviewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rating */
            rating: number;
            /** Comment */
            comment: string | null;
            /** Customer First Name */
            customer_first_name: string;
            /** Service Name */
            service_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PushConfigOut */
        PushConfigOut: {
            /** Enabled */
            enabled: boolean;
            /**
             * Public Key
             * @description Pass as applicationServerKey to pushManager.subscribe().
             */
            public_key: string | null;
        };
        /** PushKeys */
        PushKeys: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /**
         * PushSubscriptionIn
         * @description The browser's PushSubscription.toJSON().
         */
        PushSubscriptionIn: {
            /**
             * Endpoint
             * Format: uri
             */
            endpoint: string;
            keys: components["schemas"]["PushKeys"];
        };
        /** PushSubscriptionRemoveIn */
        PushSubscriptionRemoveIn: {
            /** Endpoint */
            endpoint: string;
        };
        /** ReadIn */
        ReadIn: {
            /** Sequence No */
            sequence_no: number;
        };
        /** ReportIn */
        ReportIn: {
            kind: components["schemas"]["ReportKind"];
            /**
             * Severity
             * @description 1 (minor) to 5 (urgent). Defaults by kind; safety is at least 4.
             */
            severity?: number | null;
            /** Description */
            description: string;
        };
        /**
         * ReportKind
         * @enum {string}
         */
        ReportKind: "dispute" | "safety" | "quality" | "no_show" | "payment";
        /**
         * ReportOut
         * @description The reporter's view: what they reported and what Vendy decided.
         */
        ReportOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Booking Id
             * Format: uuid
             */
            booking_id: string;
            /** Booking Reference */
            booking_reference: string;
            kind: components["schemas"]["ReportKind"];
            /** Severity */
            severity: number;
            /** Description */
            description: string;
            status: components["schemas"]["ReportStatus"];
            /** Resolution Note */
            resolution_note: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReportStatus
         * @enum {string}
         */
        ReportStatus: "open" | "investigating" | "resolved" | "closed";
        /** ResetPasswordIn */
        ResetPasswordIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Code */
            code: string;
            /** New Password */
            new_password: string;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
        };
        /**
         * RevisionStatus
         * @enum {string}
         */
        RevisionStatus: "pending" | "approved" | "declined" | "expired" | "withdrawn";
        /** SearchOut */
        SearchOut: {
            service: components["schemas"]["ServiceRef"];
            /** Items */
            items: components["schemas"]["VendorSearchResult"][];
            /** Total */
            total: number;
            /** Count */
            count: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * SearchSort
         * @enum {string}
         */
        SearchSort: "distance" | "jobs_completed" | "rating" | "price";
        /** SentMessageOut */
        SentMessageOut: {
            message: components["schemas"]["MessageOut"];
            /**
             * Notice
             * @description Set when contact details were hidden from the message. Show it to the sender.
             */
            notice: string | null;
        };
        /** ServiceRef */
        ServiceRef: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** ServiceTypeOut */
        ServiceTypeOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            default_pricing_model: components["schemas"]["PricingModel"];
            category: components["schemas"]["CategorySummary"];
            /** Suggested Labels */
            suggested_labels: components["schemas"]["SuggestedLabelOut"][];
        };
        /** ServiceTypeSummary */
        ServiceTypeSummary: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            default_pricing_model: components["schemas"]["PricingModel"];
        };
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["UserOut"];
            /**
             * Access Token
             * @description Also set as an httpOnly cookie. Use as a Bearer token for API testing.
             */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** SignupIn */
        SignupIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /**
             * Phone
             * @example 0712 345 678
             */
            phone: string;
            /**
             * Accept Terms
             * @description Accepts the current terms and privacy notice.
             */
            accept_terms: boolean;
        };
        /** SuggestedLabelOut */
        SuggestedLabelOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["UserStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "customer" | "vendor" | "admin" | "superadmin";
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "suspended" | "deleted";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VendorCard
         * @description A vendor in a list. No contact details, no exact location.
         */
        VendorCard: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            neighbourhood: components["schemas"]["NeighbourhoodRef"] | null;
            /** Distance M */
            distance_m: number;
            /** Services */
            services: string[];
            /** Price From Kes */
            price_from_kes: number | null;
            /** Rating Avg */
            rating_avg: number | null;
            /** Rating Count */
            rating_count: number;
            /** Jobs Completed */
            jobs_completed: number;
            /** Is Founding Vendor */
            is_founding_vendor: boolean;
            /** Accepts Emergency */
            accepts_emergency: boolean;
        };
        /**
         * VendorContactOut
         * @description For the customer, once the booking is confirmed. Every fetch is recorded.
         */
        VendorContactOut: {
            /** Display Name */
            display_name: string;
            /** Phone */
            phone: string;
            /** Alt Phone */
            alt_phone: string | null;
            /** Whatsapp */
            whatsapp: string | null;
            /** Email */
            email: string | null;
        };
        /**
         * VendorPublicOut
         * @description What customers see. No contact fields exist here, not even empty ones,
         *     and the location is the snapped public point.
         */
        VendorPublicOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /** Bio */
            bio: string | null;
            /** Years Experience */
            years_experience: number | null;
            neighbourhood: components["schemas"]["NeighbourhoodRef"] | null;
            /** Approx Lat */
            approx_lat: number | null;
            /** Approx Lng */
            approx_lng: number | null;
            /** Service Radius M */
            service_radius_m: number;
            /** Rating Avg */
            rating_avg: number | null;
            /** Rating Count */
            rating_count: number;
            /** Jobs Completed */
            jobs_completed: number;
            /** Confirmation Rate */
            confirmation_rate: number | null;
            /** Is Founding Vendor */
            is_founding_vendor: boolean;
            /** Accepts Emergency */
            accepts_emergency: boolean;
            /** Services */
            services: components["schemas"]["OfferedService"][];
            /** Portfolio */
            portfolio: components["schemas"]["PublicPortfolioItem"][];
        };
        /** VendorRef */
        VendorRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
        };
        /** VendorSearchResult */
        VendorSearchResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            neighbourhood: components["schemas"]["NeighbourhoodRef"] | null;
            /** Distance M */
            distance_m: number;
            /** Services */
            services: string[];
            /** Price From Kes */
            price_from_kes: number | null;
            /** Rating Avg */
            rating_avg: number | null;
            /** Rating Count */
            rating_count: number;
            /** Jobs Completed */
            jobs_completed: number;
            /** Is Founding Vendor */
            is_founding_vendor: boolean;
            /** Accepts Emergency */
            accepts_emergency: boolean;
            /** Price Items */
            price_items: components["schemas"]["PublicPriceItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_auth_verify_email_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgot_password_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_catalog_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    get_service_type_catalog_service_types__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_neighbourhoods_neighbourhoods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighbourhoodOut"][];
                };
            };
        };
    };
    search_vendors_search_vendors_get: {
        parameters: {
            query: {
                /** @description Service type slug, e.g. phone-screen-replacement. */
                service: string;
                /** @description The customer's location, or their chosen neighbourhood's centre. */
                lat: number;
                lng: number;
                /** @description Optional: vendor name or keywords. */
                q?: string | null;
                sort?: components["schemas"]["SearchSort"];
                min_jobs?: number | null;
                /** @description Cheapest price for this service, in KSh. */
                max_price?: number | null;
                max_distance_m?: number | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    popular_vendors_search_popular_get: {
        parameters: {
            query: {
                /** @description The customer's location, or their chosen neighbourhood's centre. */
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_booking_bookings__booking_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    awaiting_review_reviews_awaiting_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwaitingReviewOut"][];
                };
            };
        };
    };
    vendor_reviews_vendors__slug__reviews_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PublicReviewOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vendor_vendors__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorPublicOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings_bookings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["BookingStatus"] | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CustomerBookingSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_bookings_post: {
        parameters: {
            query?: never;
            header: {
                /** @description A unique value per booking attempt (e.g. a UUID). Retrying with the same key returns the same booking. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerBookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking_bookings__booking_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerBookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vendor_contact_bookings__booking_id__contact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_bookings__booking_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerBookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_price_change_bookings__booking_id__price_change_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerBookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_price_change_bookings__booking_id__price_change_decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerBookingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_booking_photos_bookings__booking_id__photos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPhotoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_booking_photo_bookings__booking_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_report_bookings__booking_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_reports_reports_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReportOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_report_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ConversationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                /** @description Catch up: messages after this one. */
                after_sequence_no?: number | null;
                /** @description Page back: messages before this one. */
                before_sequence_no?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentMessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_conversations__conversation_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mark_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_config_notifications_push_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushConfigOut"];
                };
            };
        };
    };
    save_push_subscription_notifications_push_subscription_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_push_subscription_notifications_push_subscription_remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionRemoveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_notifications_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
        };
    };
    set_preferences_notifications_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_media_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
